# bash completion for goskyr
# generated by king (https://github.com/miekg/king) for kong
# manually modified to add scraper name completions

_mytool_get_config() {
    local i word next

    for ((i=0; i < ${#COMP_WORDS[@]}; i++)); do
        word="${COMP_WORDS[i]}"

        case "$word" in
            --config)
                next="${COMP_WORDS[i+1]}"
                [[ -n "$next" && "$next" != -* ]] && printf '%s\n' "$next"
                return
                ;;
            -c)
                next="${COMP_WORDS[i+1]}"
                [[ -n "$next" && "$next" != -* ]] && printf '%s\n' "$next"
                return
                ;;
        esac
    done
}

_goskyr_filter() {
  COMP_REPLY=()
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done
    echo "${result[*]}"
  fi
}

_goskyr_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"
  local config="$(_mytool_get_config)"

  case "$compline" in

    'generate'*'--scraper-config')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'extract'*'--word-lists')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;
    'completion'*'--shell')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "bash zsh fish")" -- "$cur")
      ;;
    'generate'*'--config')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'extract'*'--config')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'scrape'*'--config')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'completion'*'-s')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "bash zsh fish")" -- "$cur")
      ;;
    'list'*'--config')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'scrape'*'--name')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "$(goskyr list -c "$config" -C 2>/dev/null)")" -- "$cur")
      ;;
    'generate'*'-c')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'generate'*'-s')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'extract'*'-c')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'extract'*'-w')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;
    'completion'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "--shell -s")" -- "$cur")
      ;;
    'scrape'*'-c')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'scrape'*'-n')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "$(goskyr list -c "$config" -C 2>/dev/null)")" -- "$cur")
      ;;
    'generate'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "--url -u --config -c --stdout -o --scraper-config -s --interactive -i")" -- "$cur")
      ;;
    'list'*'-c')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;
    'extract'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "--config -c --out-file -o --word-lists -w")" -- "$cur")
      ;;
    'scrape'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "--config -c --name -n --stdout -o --dry-run -D")" -- "$cur")
      ;;
    'train'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "--feature-file -f")" -- "$cur")
      ;;
    'list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "--config -c --completion -C")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goskyr_filter "completion scrape generate extract train list --help -h --version -v --debug -d")" -- "$cur")
      ;;
esac

} &&
complete -F _goskyr_completions goskyr
